const PlayerGlossary = {
  LDE: 'Left Defensive End',
  LDT: 'Left Defensive Tackle',
  RDT: 'Right Defensive Tackle',
  RDE: 'Right Defensive End',
  WLB: 'Weakside Linebacker',
  MLB: 'Middle Linebacker',
  SLB: 'Strongside Linebacker',
  LCB: 'Left Cornerback',
  SS: 'Strong Safety',
  FS: 'Free Safety',
  RCB: 'Right Cornerback',
  PK: 'Place Kicker',
  P: 'Punter',
  H: 'Holder',
  PR: 'Punt Returner',
  KR: 'Kick Returner',
  LS: 'Long Snapper',
  WR: 'Wide Receiver',
  LT: 'Left Tackle',
  LG: 'Left Guard',
  C: 'Center',
  RG: 'Right Guard',
  RT: 'Right Tackle',
  QB: 'Quarterback',
  TE: 'Tight End',
  RB: 'Running Back',
  FB: 'Fullback',
};

const InjuryGlossary = {
  P: 'Probable',
  Q: 'Questionable',
  O: 'Out',
  PUP: 'Physically unable to perform',
  SUS: 'Suspended by NFL or current team',
  IR: 'Injured reserve',
};
